//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 05:33:53 PM EEST 
//


package com.rosteach.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentInvoice"
})
@XmlRootElement(name = "DocList-Invoice")
public class DocListInvoice {

    @XmlElement(name = "Document-Invoice")
    protected List<DocListInvoice.DocumentInvoice> documentInvoice;
     
    /**
     * Gets the value of the documentInvoice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentInvoice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentInvoice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocListInvoice.DocumentInvoice }
     * 
     * 
     */
    public List<DocListInvoice.DocumentInvoice> getDocumentInvoice() {
        if (documentInvoice == null) {
            documentInvoice = new ArrayList<DocListInvoice.DocumentInvoice>();
        }
        return this.documentInvoice;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "invoiceHeader",
        "invoiceParties",
        "sellerInvoice",
        "taxInvoice",
        "ttnInvoice",
        "invoiceLines",
        "invoiceSummary"
    })
    public static class DocumentInvoice {

        @XmlElement(name = "Invoice-Header")
        protected List<DocListInvoice.DocumentInvoice.InvoiceHeader> invoiceHeader;
        @XmlElement(name = "Invoice-Parties")
        protected List<DocListInvoice.DocumentInvoice.InvoiceParties> invoiceParties;
        @XmlElement(name = "Seller-Invoice")
        protected List<DocListInvoice.DocumentInvoice.SellerInvoice> sellerInvoice;
        @XmlElement(name = "Tax-Invoice")
        protected List<DocListInvoice.DocumentInvoice.TaxInvoice> taxInvoice;
        @XmlElement(name = "TTN-Invoice")
        protected List<DocListInvoice.DocumentInvoice.TTNInvoice> ttnInvoice;
        @XmlElement(name = "Invoice-Lines")
        protected List<DocListInvoice.DocumentInvoice.InvoiceLines> invoiceLines;
        @XmlElement(name = "Invoice-Summary")
        protected List<DocListInvoice.DocumentInvoice.InvoiceSummary> invoiceSummary;

        /**
         * Gets the value of the invoiceHeader property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the invoiceHeader property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInvoiceHeader().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocListInvoice.DocumentInvoice.InvoiceHeader }
         * 
         * 
         */
        public List<DocListInvoice.DocumentInvoice.InvoiceHeader> getInvoiceHeader() {
            if (invoiceHeader == null) {
                invoiceHeader = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceHeader>();
            }
            return this.invoiceHeader;
        }

        /**
         * Gets the value of the invoiceParties property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the invoiceParties property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInvoiceParties().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocListInvoice.DocumentInvoice.InvoiceParties }
         * 
         * 
         */
        public List<DocListInvoice.DocumentInvoice.InvoiceParties> getInvoiceParties() {
            if (invoiceParties == null) {
                invoiceParties = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceParties>();
            }
            return this.invoiceParties;
        }

        /**
         * Gets the value of the sellerInvoice property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sellerInvoice property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSellerInvoice().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocListInvoice.DocumentInvoice.SellerInvoice }
         * 
         * 
         */
        public List<DocListInvoice.DocumentInvoice.SellerInvoice> getSellerInvoice() {
            if (sellerInvoice == null) {
                sellerInvoice = new ArrayList<DocListInvoice.DocumentInvoice.SellerInvoice>();
            }
            return this.sellerInvoice;
        }

        /**
         * Gets the value of the taxInvoice property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taxInvoice property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaxInvoice().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocListInvoice.DocumentInvoice.TaxInvoice }
         * 
         * 
         */
        public List<DocListInvoice.DocumentInvoice.TaxInvoice> getTaxInvoice() {
            if (taxInvoice == null) {
                taxInvoice = new ArrayList<DocListInvoice.DocumentInvoice.TaxInvoice>();
            }
            return this.taxInvoice;
        }

        /**
         * Gets the value of the ttnInvoice property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ttnInvoice property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTTNInvoice().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocListInvoice.DocumentInvoice.TTNInvoice }
         * 
         * 
         */
        public List<DocListInvoice.DocumentInvoice.TTNInvoice> getTTNInvoice() {
            if (ttnInvoice == null) {
                ttnInvoice = new ArrayList<DocListInvoice.DocumentInvoice.TTNInvoice>();
            }
            return this.ttnInvoice;
        }

        /**
         * Gets the value of the invoiceLines property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the invoiceLines property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInvoiceLines().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocListInvoice.DocumentInvoice.InvoiceLines }
         * 
         * 
         */
        public List<DocListInvoice.DocumentInvoice.InvoiceLines> getInvoiceLines() {
            if (invoiceLines == null) {
                invoiceLines = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceLines>();
            }
            return this.invoiceLines;
        }

        /**
         * Gets the value of the invoiceSummary property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the invoiceSummary property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInvoiceSummary().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocListInvoice.DocumentInvoice.InvoiceSummary }
         * 
         * 
         */
        public List<DocListInvoice.DocumentInvoice.InvoiceSummary> getInvoiceSummary() {
            if (invoiceSummary == null) {
                invoiceSummary = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceSummary>();
            }
            return this.invoiceSummary;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="EAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="InvoiceDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ContractDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "invoiceNumber",
            "ean",
            "invoiceDate",
            "contractNumber",
            "contractDate"
        })
        public static class InvoiceHeader {

            @XmlElement(name = "InvoiceNumber")
            protected String invoiceNumber;
            @XmlElement(name = "EAN")
            protected String ean;
            @XmlElement(name = "InvoiceDate", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar invoiceDate;
            @XmlElement(name = "ContractNumber")
            protected String contractNumber;
            @XmlElement(name = "ContractDate")
            protected String contractDate;

            /**
             * Gets the value of the invoiceNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInvoiceNumber() {
                return invoiceNumber;
            }

            /**
             * Sets the value of the invoiceNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvoiceNumber(String value) {
                this.invoiceNumber = value;
            }

            /**
             * Gets the value of the ean property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEAN() {
                return ean;
            }

            /**
             * Sets the value of the ean property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEAN(String value) {
                this.ean = value;
            }

            /**
             * Gets the value of the invoiceDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public XMLGregorianCalendar getInvoiceDate() {
                return invoiceDate;
            }

            /**
             * Sets the value of the invoiceDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvoiceDate(XMLGregorianCalendar value) {
                this.invoiceDate = value;
            }

            /**
             * Gets the value of the contractNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractNumber() {
                return contractNumber;
            }

            /**
             * Sets the value of the contractNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractNumber(String value) {
                this.contractNumber = value;
            }

            /**
             * Gets the value of the contractDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractDate() {
                return contractDate;
            }

            /**
             * Sets the value of the contractDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractDate(String value) {
                this.contractDate = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Lines" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="LineNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="EAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="ItemDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="InvoiceQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="InvoiceUnitNetPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="NetAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lines"
        })
        public static class InvoiceLines {

            @XmlElement(name = "Lines")
            protected List<DocListInvoice.DocumentInvoice.InvoiceLines.Lines> lines;

            /**
             * Gets the value of the lines property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the lines property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLines().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocListInvoice.DocumentInvoice.InvoiceLines.Lines }
             * 
             * 
             */
            public List<DocListInvoice.DocumentInvoice.InvoiceLines.Lines> getLines() {
                if (lines == null) {
                    lines = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceLines.Lines>();
                }
                return this.lines;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "lineNumber",
                "ean",
                "itemDescription",
                "invoiceQuantity",
                "invoiceUnitNetPrice",
                "netAmount"
            })
            public static class Lines {

                @XmlElement(name = "LineNumber")
                protected String lineNumber;
                @XmlElement(name = "EAN")
                protected String ean;
                @XmlElement(name = "ItemDescription")
                protected String itemDescription;
                @XmlElement(name = "InvoiceQuantity")
                protected String invoiceQuantity;
                @XmlElement(name = "InvoiceUnitNetPrice")
                protected String invoiceUnitNetPrice;
                @XmlElement(name = "NetAmount")
                protected String netAmount;

                /**
                 * Gets the value of the lineNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLineNumber() {
                    return lineNumber;
                }

                /**
                 * Sets the value of the lineNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLineNumber(String value) {
                    this.lineNumber = value;
                }

                /**
                 * Gets the value of the ean property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEAN() {
                    return ean;
                }

                /**
                 * Sets the value of the ean property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEAN(String value) {
                    this.ean = value;
                }

                /**
                 * Gets the value of the itemDescription property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getItemDescription() {
                    return itemDescription;
                }

                /**
                 * Sets the value of the itemDescription property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setItemDescription(String value) {
                    this.itemDescription = value;
                }

                /**
                 * Gets the value of the invoiceQuantity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInvoiceQuantity() {
                    return invoiceQuantity;
                }

                /**
                 * Sets the value of the invoiceQuantity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInvoiceQuantity(String value) {
                    this.invoiceQuantity = value;
                }

                /**
                 * Gets the value of the invoiceUnitNetPrice property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInvoiceUnitNetPrice() {
                    return invoiceUnitNetPrice;
                }

                /**
                 * Sets the value of the invoiceUnitNetPrice property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInvoiceUnitNetPrice(String value) {
                    this.invoiceUnitNetPrice = value;
                }

                /**
                 * Gets the value of the netAmount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNetAmount() {
                    return netAmount;
                }

                /**
                 * Sets the value of the netAmount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNetAmount(String value) {
                    this.netAmount = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DeliveryKod" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DeliveryName" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Buyer" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Seller" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "deliveryKod",
            "deliveryName",
            "buyer",
            "seller"
        })
        public static class InvoiceParties {

            @XmlElement(name = "DeliveryKod")
            protected List<DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryKod> deliveryKod;
            @XmlElement(name = "DeliveryName")
            protected List<DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryName> deliveryName;
            @XmlElement(name = "Buyer")
            protected List<DocListInvoice.DocumentInvoice.InvoiceParties.Buyer> buyer;
            @XmlElement(name = "Seller")
            protected List<DocListInvoice.DocumentInvoice.InvoiceParties.Seller> seller;

            /**
             * Gets the value of the deliveryKod property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the deliveryKod property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDeliveryKod().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryKod }
             * 
             * 
             */
            public List<DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryKod> getDeliveryKod() {
                if (deliveryKod == null) {
                    deliveryKod = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryKod>();
                }
                return this.deliveryKod;
            }

            /**
             * Gets the value of the deliveryName property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the deliveryName property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDeliveryName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryName }
             * 
             * 
             */
            public List<DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryName> getDeliveryName() {
                if (deliveryName == null) {
                    deliveryName = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryName>();
                }
                return this.deliveryName;
            }

            /**
             * Gets the value of the buyer property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the buyer property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBuyer().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocListInvoice.DocumentInvoice.InvoiceParties.Buyer }
             * 
             * 
             */
            public List<DocListInvoice.DocumentInvoice.InvoiceParties.Buyer> getBuyer() {
                if (buyer == null) {
                    buyer = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceParties.Buyer>();
                }
                return this.buyer;
            }

            /**
             * Gets the value of the seller property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the seller property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSeller().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocListInvoice.DocumentInvoice.InvoiceParties.Seller }
             * 
             * 
             */
            public List<DocListInvoice.DocumentInvoice.InvoiceParties.Seller> getSeller() {
                if (seller == null) {
                    seller = new ArrayList<DocListInvoice.DocumentInvoice.InvoiceParties.Seller>();
                }
                return this.seller;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "taxID"
            })
            public static class Buyer {

                @XmlElement(name = "TaxID")
                protected String taxID;

                /**
                 * Gets the value of the taxID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTaxID() {
                    return taxID;
                }

                /**
                 * Sets the value of the taxID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTaxID(String value) {
                    this.taxID = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "taxID"
            })
            public static class DeliveryKod {

                @XmlElement(name = "TaxID")
                protected String taxID;

                /**
                 * Gets the value of the taxID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTaxID() {
                    return taxID;
                }

                /**
                 * Sets the value of the taxID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTaxID(String value) {
                    this.taxID = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "taxID"
            })
            public static class DeliveryName {

                @XmlElement(name = "TaxID")
                protected String taxID;

                /**
                 * Gets the value of the taxID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTaxID() {
                    return taxID;
                }

                /**
                 * Sets the value of the taxID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTaxID(String value) {
                    this.taxID = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "taxID"
            })
            public static class Seller {

                @XmlElement(name = "TaxID")
                protected String taxID;

                /**
                 * Gets the value of the taxID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTaxID() {
                    return taxID;
                }

                /**
                 * Sets the value of the taxID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTaxID(String value) {
                    this.taxID = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TotalLines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TotalNetAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TotalTaxAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TotalGrossAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totalLines",
            "totalNetAmount",
            "totalTaxAmount",
            "totalGrossAmount"
        })
        public static class InvoiceSummary {

            @XmlElement(name = "TotalLines")
            protected String totalLines;
            @XmlElement(name = "TotalNetAmount")
            protected String totalNetAmount;
            @XmlElement(name = "TotalTaxAmount")
            protected String totalTaxAmount;
            @XmlElement(name = "TotalGrossAmount")
            protected String totalGrossAmount;

            /**
             * Gets the value of the totalLines property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalLines() {
                return totalLines;
            }

            /**
             * Sets the value of the totalLines property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalLines(String value) {
                this.totalLines = value;
            }

            /**
             * Gets the value of the totalNetAmount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalNetAmount() {
                return totalNetAmount;
            }

            /**
             * Sets the value of the totalNetAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalNetAmount(String value) {
                this.totalNetAmount = value;
            }

            /**
             * Gets the value of the totalTaxAmount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalTaxAmount() {
                return totalTaxAmount;
            }

            /**
             * Sets the value of the totalTaxAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalTaxAmount(String value) {
                this.totalTaxAmount = value;
            }

            /**
             * Gets the value of the totalGrossAmount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalGrossAmount() {
                return totalGrossAmount;
            }

            /**
             * Sets the value of the totalGrossAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalGrossAmount(String value) {
                this.totalGrossAmount = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SellerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SellerDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SellersWrite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ContractDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sellerNumber",
            "sellerDate",
            "sellersWrite",
            "contractNumber",
            "contractDate"
        })
        public static class SellerInvoice {

            @XmlElement(name = "SellerNumber")
            protected String sellerNumber;
            @XmlElement(name = "SellerDate")
            protected String sellerDate;
            @XmlElement(name = "SellersWrite")
            protected String sellersWrite;
            @XmlElement(name = "ContractNumber")
            protected String contractNumber;
            @XmlElement(name = "ContractDate")
            protected String contractDate;

            /**
             * Gets the value of the sellerNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSellerNumber() {
                return sellerNumber;
            }

            /**
             * Sets the value of the sellerNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSellerNumber(String value) {
                this.sellerNumber = value;
            }

            /**
             * Gets the value of the sellerDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSellerDate() {
                return sellerDate;
            }

            /**
             * Sets the value of the sellerDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSellerDate(String value) {
                this.sellerDate = value;
            }

            /**
             * Gets the value of the sellersWrite property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSellersWrite() {
                return sellersWrite;
            }

            /**
             * Sets the value of the sellersWrite property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSellersWrite(String value) {
                this.sellersWrite = value;
            }

            /**
             * Gets the value of the contractNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractNumber() {
                return contractNumber;
            }

            /**
             * Sets the value of the contractNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractNumber(String value) {
                this.contractNumber = value;
            }

            /**
             * Gets the value of the contractDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractDate() {
                return contractDate;
            }

            /**
             * Sets the value of the contractDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractDate(String value) {
                this.contractDate = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TTNNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TTNDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TTNAuto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ttnNumber",
            "ttnDate",
            "ttnAuto"
        })
        public static class TTNInvoice {

            @XmlElement(name = "TTNNumber")
            protected String ttnNumber;
            @XmlElement(name = "TTNDate")
            protected String ttnDate;
            @XmlElement(name = "TTNAuto")
            protected String ttnAuto;

            /**
             * Gets the value of the ttnNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTTNNumber() {
                return ttnNumber;
            }

            /**
             * Sets the value of the ttnNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTTNNumber(String value) {
                this.ttnNumber = value;
            }

            /**
             * Gets the value of the ttnDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTTNDate() {
                return ttnDate;
            }

            /**
             * Sets the value of the ttnDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTTNDate(String value) {
                this.ttnDate = value;
            }

            /**
             * Gets the value of the ttnAuto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTTNAuto() {
                return ttnAuto;
            }

            /**
             * Sets the value of the ttnAuto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTTNAuto(String value) {
                this.ttnAuto = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TaxNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TaxDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TaxRegister" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TaxWrite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "taxNumber",
            "taxDate",
            "taxRegister",
            "taxWrite"
        })
        public static class TaxInvoice {

        	@XmlElement(name = "TaxNumber")
            protected int taxNumber;
            @XmlElement(name = "TaxDate")
            protected String taxDate;
            @XmlElement(name = "TaxRegister")
            protected String taxRegister;
            @XmlElement(name = "TaxWrite")
            protected String taxWrite;

            /**
             * Gets the value of the taxNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public int getTaxNumber() {
                return taxNumber;
            }

            /**
             * Sets the value of the taxNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxNumber(int value) {
                this.taxNumber = value;
            }

            /**
             * Gets the value of the taxDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxDate() {
                return taxDate;
            }

            /**
             * Sets the value of the taxDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxDate(String value) {
                this.taxDate = value;
            }

            /**
             * Gets the value of the taxRegister property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxRegister() {
                return taxRegister;
            }

            /**
             * Sets the value of the taxRegister property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxRegister(String value) {
                this.taxRegister = value;
            }

            /**
             * Gets the value of the taxWrite property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxWrite() {
                return taxWrite;
            }

            /**
             * Sets the value of the taxWrite property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxWrite(String value) {
                this.taxWrite = value;
            }

        }

    }

}
