//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 05:33:53 PM EEST 
//


package com.rosteach.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rosteach.xm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rosteach.xm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocListInvoice }
     * 
     */
    public DocListInvoice createDocListInvoice() {
        return new DocListInvoice();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice }
     * 
     */
    public DocListInvoice.DocumentInvoice createDocListInvoiceDocumentInvoice() {
        return new DocListInvoice.DocumentInvoice();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceLines }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceLines createDocListInvoiceDocumentInvoiceInvoiceLines() {
        return new DocListInvoice.DocumentInvoice.InvoiceLines();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceParties }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceParties createDocListInvoiceDocumentInvoiceInvoiceParties() {
        return new DocListInvoice.DocumentInvoice.InvoiceParties();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceHeader }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceHeader createDocListInvoiceDocumentInvoiceInvoiceHeader() {
        return new DocListInvoice.DocumentInvoice.InvoiceHeader();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.SellerInvoice }
     * 
     */
    public DocListInvoice.DocumentInvoice.SellerInvoice createDocListInvoiceDocumentInvoiceSellerInvoice() {
        return new DocListInvoice.DocumentInvoice.SellerInvoice();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.TaxInvoice }
     * 
     */
    public DocListInvoice.DocumentInvoice.TaxInvoice createDocListInvoiceDocumentInvoiceTaxInvoice() {
        return new DocListInvoice.DocumentInvoice.TaxInvoice();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.TTNInvoice }
     * 
     */
    public DocListInvoice.DocumentInvoice.TTNInvoice createDocListInvoiceDocumentInvoiceTTNInvoice() {
        return new DocListInvoice.DocumentInvoice.TTNInvoice();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceSummary }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceSummary createDocListInvoiceDocumentInvoiceInvoiceSummary() {
        return new DocListInvoice.DocumentInvoice.InvoiceSummary();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceLines.Lines }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceLines.Lines createDocListInvoiceDocumentInvoiceInvoiceLinesLines() {
        return new DocListInvoice.DocumentInvoice.InvoiceLines.Lines();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryKod }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryKod createDocListInvoiceDocumentInvoiceInvoicePartiesDeliveryKod() {
        return new DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryKod();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryName }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryName createDocListInvoiceDocumentInvoiceInvoicePartiesDeliveryName() {
        return new DocListInvoice.DocumentInvoice.InvoiceParties.DeliveryName();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceParties.Buyer }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceParties.Buyer createDocListInvoiceDocumentInvoiceInvoicePartiesBuyer() {
        return new DocListInvoice.DocumentInvoice.InvoiceParties.Buyer();
    }

    /**
     * Create an instance of {@link DocListInvoice.DocumentInvoice.InvoiceParties.Seller }
     * 
     */
    public DocListInvoice.DocumentInvoice.InvoiceParties.Seller createDocListInvoiceDocumentInvoiceInvoicePartiesSeller() {
        return new DocListInvoice.DocumentInvoice.InvoiceParties.Seller();
    }

}
